In [1]:
import pandas as pd
import numpy as np

In [2]:
from bs4 import BeautifulSoup
import requests
import json
import secrets # file that contains your API key
import time
CACHE_FILE_NAME = 'cacheSite_Scrape.json'

def load_cache():
    try:
        cache_file = open(CACHE_FILE_NAME, 'r')
        cache_file_contents = cache_file.read()
        cache = json.loads(cache_file_contents)
        cache_file.close()
    except:
        cache = {}
    return cache

def save_cache(cache):
    cache_file = open(CACHE_FILE_NAME, 'w')
    contents_to_write = json.dumps(cache)
    cache_file.write(contents_to_write)
    cache_file.close()

def make_url_request_using_cache(url, cache, params=None, type='text'):
    if (url in cache.keys()):  # the url is our unique key
        print("Using cache")
        return cache[url]
    else:
        print("Fetching")
        time.sleep(1)
        response = requests.get(url)
        if type == 'json':
            cache[url] = response.json()
        else:
            cache[url] = response.text
        save_cache(cache)
        return cache[url]

CACHE_DICT = load_cache()  
url = 'https://bigbangtrans.wordpress.com/'
page = make_url_request_using_cache(url, CACHE_DICT)
soup = BeautifulSoup(page, 'html.parser')

epi_scrape = soup.find_all('ul')[0].find_all('li')
result = []
for i in epi_scrape[1:]:
    result.append(i.find_all('a')[0].text.replace('\xa0',' '))
result

Fetching

['Series 01 Episode 01 – Pilot Episode',
 'Series 01 Episode 02 – The Big Bran Hypothesis',
 'Series 01 Episode 03 – The Fuzzy Boots Corollary',
 'Series 01 Episode 04 – The Luminous Fish Effect',
 'Series 01 Episode 05 – The Hamburger Postulate',
 'Series 01 Episode 06 – The Middle Earth Paradigm',
 'Series 01 Episode 07 – The Dumpling Paradox',
 'Series 01 Episode 08 – The Grasshopper Experiment',
 'Series 01 Episode 09 – The Cooper-Hofstadter Polarization',
 'Series 01 Episode 10 – The Loobenfeld Decay',
 'Series 01 Episode 11 – The Pancake Batter Anomaly',
 'Series 01 Episode 12 – The Jerusalem Duality',
 'Series 01 Episode 13 – The Bat Jar Conjecture',
 'Series 01 Episode 14 – The Nerdvana Annihilation',
 'Series 01 Episode 15 – The Porkchop Indeterminacy',
 'Series 01 Episode 16 – The Peanut Reaction',
 'Series 01 Episode 17 – The Tangerine Factor',
 'Series 02 Episode 01 – The Bad Fish Paradigm',
 'Series 02 Episode 02 – The Codpiece Topology',
 'Series 02 Episode 03 – The Barbarian Sublimation',
 'Series 02 Episode 04 – The Griffin Equivalency',
 'Series 02 Episode 05 – The Euclid Alternative',
 'Series 02 Episode 06 – The Cooper-Nowitzki Theorem',
 'Series 02 Episode 07 – The Panty Pinata Polarization',
 'Series 02 Episode 08 – The Lizard-Spock Expansion',
 'Series 02 Episode 09 – The White Asparagus Triangulation',
 'Series 02 Episode 10 – The Vartabedian Conundrum',
 'Series 02 Episode 11 – The Bath Item Gift Hypothesis',
 'Series 02 Episode 12 – The Killer Robot Instability',
 'Series 02 Episode 13 – The Friendship Algorithm',
 'Series 02 Episode 14 – The Financial Permeability',
 'Series 02 Episode 15 – The Maternal Capacitance',
 'Series 02 Episode 16 – The Cushion Saturation',
 'Series 02 Episode 17 – The Terminator Decoupling',
 'Series 02 Episode 18 – The Work Song Nanocluster',
 'Series 02 Episode 19 – The Dead Hooker Juxtaposition',
 'Series 02 Episode 20 – The Hofstadter Isotope',
 'Series 02 Episode 21 – The Vegas Renormalization',
 'Series 02 Episode 22 – The Classified Materials Turbulence',
 'Series 02 Episode 23 – The Monopolar Expedition',
 'Series 03 Episode 01 – The Electric Can Opener Fluctuation',
 'Series 03 Episode 02 – The Jiminy Conjecture',
 'Series 03 Episode 03 – The Gothowitz Deviation',
 'Series 03 Episode 04 – The Pirate Solution',
 'Series 03 Episode 05 – The Creepy Candy Coating Corollary',
 'Series 03 Episode 06 – The Cornhusker Vortex',
 'Series 03 Episode 07 – The Guitarist Amplification',
 'Series 03 Episode 08 – The Adhesive Duck Deficiency',
 'Series 03 Episode 09 – The Vengeance Formulation',
 'Series 03 Episode 10 – The Gorilla Experiment',
 'Series 03 Episode 11 – The Maternal Congruence',
 'Series 03 Episode 12 – The Psychic Vortex',
 'Series 03 Episode 13 – The Bozeman Reaction',
 'Series 03 Episode 14 – The Einstein Approximation',
 'Series 03 Episode 15 – The Large Hadron Collision',
 'Series 03 Episode 16 – The Excelsior Acquisition',
 'Series 03 Episode 17 – The Precious Fragmentation',
 'Series 03 Episode 18 – The Pants Alternative',
 'Series 03 Episode 19 – The Wheaton Recurrence',
 'Series 03 Episode 20 – The Spaghetti Catalyst',
 'Series 03 Episode 21 – The Plimpton Stimulation',
 'Series 03 Episode 22 – The Staircase Implementation',
 'Series 03 Episode 23 – The Lunar Excitation',
 'Series 04 Episode 01 – The Robotic Manipulation',
 'Series 04 Episode 02 – The Cruciferous Vegetable Amplification',
 'Series 04 Episode 03 – The Zazzy Substitution',
 'Series 04 Episode 04 – The Hot Troll Deviation',
 'Series 04 Episode 05 – The Desperation Emanation',
 'Series 04 Episode 06 – The Irish Pub Formulation',
 'Series 04 Episode 07 – The Apology Insufficiency',
 'Series 04 Episode 08 – The 21 Second Excitation',
 'Series 04 Episode 09 – The Boyfriend Complexity',
 'Series 04 Episode 10 – The Alien Parasite Hypothesis',
 'Series 04 Episode 11 – The Justice League Recombination',
 'Series 04 Episode 12 – The Bus Pants Utilization',
 'Series 04 Episode 13 – The Love Car Displacement',
 'Series 04 Episode 14 – The Thespian Catalyst',
 'Series 04 Episode 15 – The Benefactor Factor',
 'Series 04 Episode 16 – The Cohabitation Formulation',
 'Series 04 Episode 17 – The Toast Derivation',
 'Series 04 Episode 18 – The Prestidigitation Approximation',
 'Series 04 Episode 19 – The Zarnecki Incursion',
 'Series 04 Episode 20 – The Herb Garden Germination',
 'Series 04 Episode 21 – The Agreement Dissection',
 'Series 04 Episode 22 – The Wildebeest Implementation',
 'Series 04 Episode 23 – The Engagement Reaction',
 'Series 04 Episode 24 – The Roommate Transmogrification',
 'Series 05 Episode 01 – The Skank Reflex Analysis',
 'Series 05 Episode 02 – The Infestation Hypothesis',
 'Series 05 Episode 03 – The Pulled Groin Extrapolation',
 'Series 05 Episode 04 – The Wiggly Finger Catalyst',
 'Series 05 Episode 05 – The Russian Rocket Reaction',
 'Series 05 Episode 06 – The Rhinitis Revelation',
 'Series 05 Episode 07 – The Good Guy Fluctuation',
 'Series 05 Episode 08 – The Isolation Permutation',
 'Series 05 Episode 09 – The Ornithophobia Diffusion',
 'Series 05 Episode 10 – The Flaming Spittoon Acquisition',
 'Series 05 Episode 11 – The Speckerman Recurrence',
 'Series 05 Episode 12 – The Shiny Trinket Maneouvre',
 'Series 05 Episode 13 – The Recombination Hypothesis',
 'Series 05 Episode 14 – The Beta Test Initiation',
 'Series 05 Episode 15 – The Friendship Contraction',
 'Series 05 Episode 16 – The Vacation Solution',
 'Series 05 Episode 17 – The Rothman Disintegration',
 'Series 05 Episode 18 – The Werewolf Transformation',
 'Series 05 Episode 19 – The Weekend Vortex',
 'Series 05 Episode 20 – The Transporter Malfunction',
 'Series 05 Episode 21 – The Hawking Excitation',
 'Series 05 Episode 22 – The Stag Convergence',
 'Series 05 Episode 23 – The Launch Acceleration',
 'Series 05 Episode 24 – The Countdown Reflection',
 'Series 06 Episode 01 – The Date Night Variable',
 'Series 06 Episode 02 – The Decoupling Fluctuation',
 'Series 06 Episode 03 – The Higgs Boson Observation',
 'Series 06 Episode 04 – The Re-Entry Minimization',
 'Series 06 Episode 05 – The Holographic Excitation',
 'Series 06 Episode 06 – The Extract Obliteration',
 'Series 06 Episode 07 – The Habitation Configuration',
 'Series 06 Episode 08 – The 43 Peculiarity',
 'Series 06 Episode 09 – The Parking Spot Escalation',
 'Series 06 Episode 10 – The Fish Guts Displacement',
 'Series 06 Episode 11 – The Santa Simulation',
 'Series 06 Episode 12 – The Egg Salad Equivalency',
 'Series 06 Episode 13 – The Bakersfield Expedition',
 'Series 06 Episode 14 – The Cooper/Kripke Inversion',
 'Series 06 Episode 15 – The Spoiler Alert Segmentation',
 'Series 06 Episode 16 – The Tangible Affection Proof',
 'Series 06 Episode 17 – The Monster Isolation',
 'Series 06 Episode 18 – The Contractual Obligation Implementation',
 'Series 06 Episode 19 – The Closet Reconfiguration',
 'Series 06 Episode 20 – The Tenure Turbulence',
 'Series 06 Episode 21 – The Closure Alternative',
 'Series 06 Episode 22 – The Proton Resurgence',
 'Series 06 Episode 23 – The Love Spell Potential',
 'Series 06 Episode 24 – The Bon Voyage Reaction',
 'Series 07 Episode 01 – The Hofstadter Insufficiency',
 'Series 07 Episode 02 – The Deception Verification',
 'Series 07 Episode 03 – The Scavenger Vortex',
 'Series 07 Episode 04 – The Raiders Minimization',
 'Series 07 Episode 05 – The Workplace Proximity',
 'Series 07 Episode 06 – The Romance Resonance',
 'Series 07 Episode 07 – The Proton Displacement',
 'Series 07 Episode 08 – The Itchy Brain Simulation',
 'Series 07 Episode 09 – The Thanksgiving Decoupling',
 'Series 07 Episode 10 – The Discovery Dissipation',
 'Series 07 Episode 11 – The Cooper Extraction',
 'Series 07 Episode 12 – The Hesitation Ramification',
 'Series 07 Episode 13 – The Occupation Recalibration',
 'Series 07 Episode 14 – The Convention Conundrum',
 'Series 07 Episode 15 – The Locomotive Manipulation',
 'Series 07 Episode 16 – The Table Polarisation',
 'Series 07 Episode 17 – The Friendship Turbulence',
 'Series 07 Episode 18 – The Mommy Observation',
 'Series 07 Episode 19 – The Indecision Amalgamation',
 'Series 07 Episode 20 – The Relationship Diremption',
 'Series 07 Episode 21 – The Anything Can Happen Recurrence',
 'Series 07 Episode 22 – The Proton Transmogrification',
 'Series 07 Episode 23 – The Gorilla Dissolution',
 'Series 07 Episode 24 – The Status Quo Combustion',
 'Series 08 Episode 01 – The Locomotion Interruption',
 'Series 08 Episode 02 – The Junior Professor Solution',
 'Series 08 Episode 03 – The First Pitch Insufficiency',
 'Series 08 Episode 04 – The Hook-Up Reverbration',
 'Series 08 Episode 05 – The Focus Attenuation',
 'Series 08 Episode 06 – The Expedition Approximation',
 'Series 08 Episode 07 – The Misinterpretation Agitation',
 'Series 08 Episode 08 – The Prom Equivalency',
 'Series 08 Episode 09 – The Septum Deviation',
 'Series 08 Episode 10 – The Champagne Reflection',
 'Series 08 Episode 11 – The Clean Room Infiltration',
 'Series 08 Episode 12 – The Space Probe Disintegration',
 'Series 08 Episode 13 – The Anxiety Optimisation',
 'Series 08 Episode 14 – The Troll Manifestation',
 'Series 08 Episode 15 – The Comic Book Store Regeneration',
 'Series 08 Episode 16 – The Intimacy Acceleration',
 'Series 08 Episode 17 – The Colonization Application',
 'Series 08 Episode 18 – The Leftover Thermalization',
 'Series 08 Episode 19 – The Skywalker Incursion',
 'Series 08 Episode 20 – The Fortification Implementation',
 'Series 08 Episode 21 – The Communication Deterioration',
 'Series 08 Episode 22 – The Graduation Transmission',
 'Series 08 Episode 23 – The Maternal Combustion',
 'Series 08 Episode 24 – The Commitment Determination',
 'Series 09 Episode 01 – The Matrimonial Momentum',
 'Series 09 Episode 02 – The Separation Oscillation',
 'Series 09 Episode 03 – The Batchelor Party Corrosion',
 'Series 09 Episode 04 – The 2003 Approximation',
 'Series 09 Episode 05 – The Perspiration Implementation',
 'Series 09 Episode 06 – The Helium Insufficiency',
 'Series 09 Episode 07 – The Spock Resonance',
 'Series 09 Episode 08 – The Mystery Date Observation',
 'Series 09 Episode 09 – The Platonic Permutation',
 'Series 09 Episode 10 – The Earworm Reverberation',
 'Series 09 Episode 11 – The Opening Night Excitation',
 'Series 09 Episode 12 – The Sales Call Sublimation',
 'Series 09 Episode 13 – The Empathy Optimisation',
 'Series 09 Episode 14 – The Meemaw Materialisation',
 'Series 09 Episode 15 – The Valentino Submergence',
 'Series 09 Episode 16 – The Positive Negative Reaction',
 'Series 09 Episode 17 – The Celebration Experimentation',
 'Series 09 Episode 18 – The Application Deterioration',
 'Series 09 Episode 19 – The Solder Excursion Diversion',
 'Series 09 Episode 20 – The Big Bear Precipitation',
 'Series 09 Episode 21 – The Viewing Party Combustion',
 'Series 09 Episode 22 – The Fermentation Bifurcation',
 'Series 09 Episode 23 – The Line Substitution Solution',
 'Series 09 Episode 24 – The Convergence Convergence',
 'Series 10 Episode 01 – The Conjugal Conjecture',
 'Series 10 Episode 02 – The Military Miniturization',
 'Series 10 Episode 03 -The Dependence Transcendence',
 'Series 10 Episode 04 – The Cohabitation Experimentation',
 'Series 10 Episode 05 – The Hot Tub Contamination',
 'Series 10 Episode 06 – The Foetal Kick Catalyst',
 'Series 10 Episode 07 – The Veracity Elasticity',
 'Series 10 Episode 08 – The Brain Bowl Incubation',
 'Series 10 Episode 09 – The Geology Elevation',
 'Series 10 Episode 10 – The Property Division Collision',
 'Series 10 Episode 11 – The Birthday Synchronicity',
 'Series 10 Episode 12 – The Holiday Summation',
 'Series 10 Episode 13 – The Romance Recalibration',
 'Series 10 Episode 14 – The Emotion Detection Automation',
 'Series 10 Episode 15 – The Locomotion Reverberation',
 'Series 10 Episode 16 – The Allowance Evaporation',
 'Series 10 Episode 17 – The Comic-Con Conundrum',
 'Series 10 Episode 18 – The Escape Hatch Identification',
 'Series 10 Episode 19 – The Collaboration Fluctuation',
 'Series 10 Episode 20 – The Recollection Dissipation',
 'Series 10 Episode 21 – The Separation Agitation',
 'Series 10 Episode 22 – The Cognition Regeneration',
 'Series 10 Episode 23 – The Gyroscopic Collapse',
 'Series 10 Episode 24 – The Long Distance Dissonance']

In [66]:
import sqlite3 
import re
def insert_data(idx, serie, episode, title):
    connection = sqlite3.connect("db.sqlite3")
    cursor = connection.cursor()
    query = "INSERT INTO searchengine_episode (id, serie, episode, title) VALUES ({},'{}','{}','{}');".format(idx, serie, episode, title)
    print(query)
    cursor.execute(query)
    connection.commit()
    connection.close()


for idx, i in enumerate(result):
    insert_data(idx, i[7:9], i[18:20], i[23:])
    
# insert_data(2, result[1][7:9], result[1][18:20], result[1][23:])

INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (0,'01','01','Pilot Episode');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (1,'01','02','The Big Bran Hypothesis');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (2,'01','03','The Fuzzy Boots Corollary');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (3,'01','04','The Luminous Fish Effect');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (4,'01','05','The Hamburger Postulate');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (5,'01','06','The Middle Earth Paradigm');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (6,'01','07','The Dumpling Paradox');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (7,'01','08','The Grasshopper Experiment');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (8,'01','09','The Cooper-Hofstadter Polarization');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (9,'01','10','The Loobenfeld Decay');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (10,'01','11','The Pancake Batter Anomaly');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (11,'01','12','The Jerusalem Duality');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (12,'01','13','The Bat Jar Conjecture');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (13,'01','14','The Nerdvana Annihilation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (14,'01','15','The Porkchop Indeterminacy');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (15,'01','16','The Peanut Reaction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (16,'01','17','The Tangerine Factor');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (17,'02','01','The Bad Fish Paradigm');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (18,'02','02','The Codpiece Topology');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (19,'02','03','The Barbarian Sublimation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (20,'02','04','The Griffin Equivalency');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (21,'02','05','The Euclid Alternative');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (22,'02','06','The Cooper-Nowitzki Theorem');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (23,'02','07','The Panty Pinata Polarization');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (24,'02','08','The Lizard-Spock Expansion');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (25,'02','09','The White Asparagus Triangulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (26,'02','10','The Vartabedian Conundrum');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (27,'02','11','The Bath Item Gift Hypothesis');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (28,'02','12','The Killer Robot Instability');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (29,'02','13','The Friendship Algorithm');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (30,'02','14','The Financial Permeability');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (31,'02','15','The Maternal Capacitance');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (32,'02','16','The Cushion Saturation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (33,'02','17','The Terminator Decoupling');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (34,'02','18','The Work Song Nanocluster');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (35,'02','19','The Dead Hooker Juxtaposition');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (36,'02','20','The Hofstadter Isotope');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (37,'02','21','The Vegas Renormalization');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (38,'02','22','The Classified Materials Turbulence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (39,'02','23','The Monopolar Expedition');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (40,'03','01','The Electric Can Opener Fluctuation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (41,'03','02','The Jiminy Conjecture');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (42,'03','03','The Gothowitz Deviation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (43,'03','04','The Pirate Solution');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (44,'03','05','The Creepy Candy Coating Corollary');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (45,'03','06','The Cornhusker Vortex');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (46,'03','07','The Guitarist Amplification');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (47,'03','08','The Adhesive Duck Deficiency');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (48,'03','09','The Vengeance Formulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (49,'03','10','The Gorilla Experiment');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (50,'03','11','The Maternal Congruence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (51,'03','12','The Psychic Vortex');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (52,'03','13','The Bozeman Reaction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (53,'03','14','The Einstein Approximation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (54,'03','15','The Large Hadron Collision');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (55,'03','16','The Excelsior Acquisition');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (56,'03','17','The Precious Fragmentation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (57,'03','18','The Pants Alternative');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (58,'03','19','The Wheaton Recurrence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (59,'03','20','The Spaghetti Catalyst');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (60,'03','21','The Plimpton Stimulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (61,'03','22','The Staircase Implementation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (62,'03','23','The Lunar Excitation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (63,'04','01','The Robotic Manipulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (64,'04','02','The Cruciferous Vegetable Amplification');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (65,'04','03','The Zazzy Substitution');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (66,'04','04','The Hot Troll Deviation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (67,'04','05','The Desperation Emanation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (68,'04','06','The Irish Pub Formulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (69,'04','07','The Apology Insufficiency');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (70,'04','08','The 21 Second Excitation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (71,'04','09','The Boyfriend Complexity');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (72,'04','10','The Alien Parasite Hypothesis');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (73,'04','11','The Justice League Recombination');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (74,'04','12','The Bus Pants Utilization');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (75,'04','13','The Love Car Displacement');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (76,'04','14','The Thespian Catalyst');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (77,'04','15','The Benefactor Factor');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (78,'04','16','The Cohabitation Formulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (79,'04','17','The Toast Derivation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (80,'04','18','The Prestidigitation Approximation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (81,'04','19','The Zarnecki Incursion');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (82,'04','20','The Herb Garden Germination');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (83,'04','21','The Agreement Dissection');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (84,'04','22','The Wildebeest Implementation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (85,'04','23','The Engagement Reaction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (86,'04','24','The Roommate Transmogrification');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (87,'05','01','The Skank Reflex Analysis');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (88,'05','02','The Infestation Hypothesis');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (89,'05','03','The Pulled Groin Extrapolation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (90,'05','04','The Wiggly Finger Catalyst');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (91,'05','05','The Russian Rocket Reaction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (92,'05','06','The Rhinitis Revelation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (93,'05','07','The Good Guy Fluctuation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (94,'05','08','The Isolation Permutation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (95,'05','09','The Ornithophobia Diffusion');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (96,'05','10','The Flaming Spittoon Acquisition');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (97,'05','11','The Speckerman Recurrence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (98,'05','12','The Shiny Trinket Maneouvre');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (99,'05','13','The Recombination Hypothesis');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (100,'05','14','The Beta Test Initiation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (101,'05','15','The Friendship Contraction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (102,'05','16','The Vacation Solution');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (103,'05','17','The Rothman Disintegration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (104,'05','18','The Werewolf Transformation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (105,'05','19','The Weekend Vortex');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (106,'05','20','The Transporter Malfunction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (107,'05','21','The Hawking Excitation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (108,'05','22','The Stag Convergence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (109,'05','23','The Launch Acceleration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (110,'05','24','The Countdown Reflection');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (111,'06','01','The Date Night Variable');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (112,'06','02','The Decoupling Fluctuation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (113,'06','03','The Higgs Boson Observation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (114,'06','04','The Re-Entry Minimization');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (115,'06','05','The Holographic Excitation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (116,'06','06','The Extract Obliteration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (117,'06','07','The Habitation Configuration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (118,'06','08','The 43 Peculiarity');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (119,'06','09','The Parking Spot Escalation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (120,'06','10','The Fish Guts Displacement');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (121,'06','11','The Santa Simulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (122,'06','12','The Egg Salad Equivalency');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (123,'06','13','The Bakersfield Expedition');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (124,'06','14','The Cooper/Kripke Inversion');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (125,'06','15','The Spoiler Alert Segmentation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (126,'06','16','The Tangible Affection Proof');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (127,'06','17','The Monster Isolation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (128,'06','18','The Contractual Obligation Implementation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (129,'06','19','The Closet Reconfiguration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (130,'06','20','The Tenure Turbulence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (131,'06','21','The Closure Alternative');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (132,'06','22','The Proton Resurgence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (133,'06','23','The Love Spell Potential');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (134,'06','24','The Bon Voyage Reaction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (135,'07','01','The Hofstadter Insufficiency');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (136,'07','02','The Deception Verification');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (137,'07','03','The Scavenger Vortex');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (138,'07','04','The Raiders Minimization');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (139,'07','05','The Workplace Proximity');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (140,'07','06','The Romance Resonance');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (141,'07','07','The Proton Displacement');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (142,'07','08','The Itchy Brain Simulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (143,'07','09','The Thanksgiving Decoupling');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (144,'07','10','The Discovery Dissipation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (145,'07','11','The Cooper Extraction');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (146,'07','12','The Hesitation Ramification');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (147,'07','13','The Occupation Recalibration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (148,'07','14','The Convention Conundrum');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (149,'07','15','The Locomotive Manipulation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (150,'07','16','The Table Polarisation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (151,'07','17','The Friendship Turbulence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (152,'07','18','The Mommy Observation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (153,'07','19','The Indecision Amalgamation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (154,'07','20','The Relationship Diremption');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (155,'07','21','The Anything Can Happen Recurrence');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (156,'07','22','The Proton Transmogrification');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (157,'07','23','The Gorilla Dissolution');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (158,'07','24','The Status Quo Combustion');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (159,'08','01','The Locomotion Interruption');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (160,'08','02','The Junior Professor Solution');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (161,'08','03','The First Pitch Insufficiency');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (162,'08','04','The Hook-Up Reverbration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (163,'08','05','The Focus Attenuation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (164,'08','06','The Expedition Approximation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (165,'08','07','The Misinterpretation Agitation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (166,'08','08','The Prom Equivalency');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (167,'08','09','The Septum Deviation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (168,'08','10','The Champagne Reflection');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (169,'08','11','The Clean Room Infiltration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (170,'08','12','The Space Probe Disintegration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (171,'08','13','The Anxiety Optimisation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (172,'08','14','The Troll Manifestation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (173,'08','15','The Comic Book Store Regeneration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (174,'08','16','The Intimacy Acceleration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (175,'08','17','The Colonization Application');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (176,'08','18','The Leftover Thermalization');

INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (216,'10','10','The Property Division Collision');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (217,'10','11','The Birthday Synchronicity');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (218,'10','12','The Holiday Summation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (219,'10','13','The Romance Recalibration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (220,'10','14','The Emotion Detection Automation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (221,'10','15','The Locomotion Reverberation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (222,'10','16','The Allowance Evaporation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (223,'10','17','The Comic-Con Conundrum');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (224,'10','18','The Escape Hatch Identification');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (225,'10','19','The Collaboration Fluctuation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (226,'10','20','The Recollection Dissipation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (227,'10','21','The Separation Agitation');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (228,'10','22','The Cognition Regeneration');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (229,'10','23','The Gyroscopic Collapse');
INSERT INTO searchengine_episode (id, serie, episode, title) VALUES (230,'10','24','The Long Distance Dissonance');

In [111]:
import sqlite3 
import re
def load_user():
    connection = sqlite3.connect("db.sqlite3")
    cursor = connection.cursor()
    query = "SELECT id, username FROM auth_user"
    result = cursor.execute(query).fetchall()
    connection.close()
    return result
users = load_user()
users

[(3, 'Cora'),
 (7, 'Hexin'),
 (5, 'Sq'),
 (8, 'Sqsq'),
 (2, 'Yier'),
 (4, 'Yisen'),
 (6, 'Yisenw'),
 (1, 'zhanghexin')]

In [112]:
import sqlite3 
import re
def load_rating():
    connection = sqlite3.connect("db.sqlite3")
    cursor = connection.cursor()
    query = "SELECT * FROM searchengine_fav"
    result = cursor.execute(query).fetchall()
    connection.close()
    return result
ratings = load_rating()
ratings

[(9, 5, 3, 1),
 (10, 2, 4, 1),
 (11, 2, 5, 1),
 (12, 5, 6, 1),
 (13, 1, 7, 1),
 (14, 1, 17, 1),
 (15, 3, 15, 1),
 (16, 3, 10, 1),
 (17, 3, 21, 1),
 (18, 5, 29, 1),
 (19, 5, 27, 1),
 (20, 5, 37, 1),
 (21, 5, 44, 1),
 (22, 3, 63, 1),
 (23, 5, 69, 1),
 (24, 5, 71, 1),
 (25, 5, 93, 1),
 (26, 5, 105, 1),
 (27, 5, 111, 1),
 (28, 5, 121, 1),
 (29, 5, 133, 1),
 (30, 5, 219, 1),
 (31, 5, 217, 1),
 (32, 5, 218, 1),
 (33, 5, 202, 1),
 (34, 3, 206, 1),
 (35, 3, 208, 1),
 (36, 3, 214, 1),
 (37, 1, 157, 1),
 (38, 5, 154, 1),
 (39, 1, 35, 1),
 (40, 3, 49, 1),
 (41, 1, 57, 1),
 (42, 3, 62, 1),
 (43, 3, 66, 1),
 (44, 5, 79, 1),
 (45, 4, 75, 1),
 (46, 5, 101, 1),
 (47, 5, 102, 1),
 (48, 4, 120, 1),
 (49, 4, 122, 1),
 (50, 5, 151, 1),
 (51, 5, 152, 1),
 (52, 1, 145, 1),
 (53, 2, 169, 1),
 (54, 2, 170, 1),
 (55, 2, 171, 1),
 (56, 2, 193, 1),
 (57, 4, 225, 1),
 (58, 2, 211, 1),
 (59, 5, 0, 3),
 (60, 4, 3, 3),
 (61, 4, 4, 3),
 (62, 4, 6, 3),
 (63, 5, 7, 3),
 (64, 1, 9, 3),
 (65, 3, 10, 3),
 (66, 1, 17, 3),
 (67, 3, 19, 3),
 (68, 3, 21, 3),
 (69, 5, 28, 3),
 (70, 5, 30, 3),
 (71, 3, 44, 3),
 (72, 5, 47, 3),
 (73, 5, 49, 3),
 (74, 4, 20, 3),
 (75, 5, 63, 3),
 (76, 1, 69, 3),
 (77, 5, 70, 3),
 (78, 1, 79, 3),
 (79, 2, 83, 3),
 (80, 4, 88, 3),
 (81, 4, 94, 3),
 (82, 2, 97, 3),
 (83, 3, 100, 3),
 (84, 3, 105, 3),
 (85, 3, 102, 3),
 (86, 3, 101, 3),
 (87, 1, 111, 3),
 (88, 3, 114, 3),
 (89, 1, 116, 3),
 (90, 4, 118, 3),
 (91, 2, 119, 3),
 (92, 3, 120, 3),
 (93, 3, 121, 3),
 (94, 3, 122, 3),
 (95, 1, 125, 3),
 (96, 5, 127, 3),
 (97, 1, 129, 3),
 (98, 5, 130, 3),
 (99, 5, 139, 3),
 (100, 3, 140, 3),
 (101, 4, 143, 3),
 (102, 2, 145, 3),
 (103, 2, 157, 3),
 (104, 1, 161, 3),
 (105, 4, 180, 3),
 (107, 4, 186, 3),
 (108, 4, 194, 3),
 (109, 4, 198, 3),
 (110, 3, 202, 3),
 (111, 1, 208, 3),
 (112, 5, 220, 3),
 (113, 1, 35, 3),
 (114, 4, 93, 3),
 (115, 5, 195, 3),
 (116, 3, 217, 3),
 (117, 3, 218, 3),
 (118, 3, 174, 3),
 (119, 3, 163, 3),
 (120, 4, 171, 3),
 (121, 5, 173, 3),
 (122, 5, 160, 3),
 (125, 3, 0, 2),
 (126, 4, 1, 2),
 (127, 5, 2, 2),
 (128, 3, 3, 2),
 (129, 5, 4, 2),
 (130, 4, 5, 2),
 (131, 5, 6, 2),
 (132, 3, 7, 2),
 (133, 4, 8, 2),
 (134, 2, 9, 2),
 (135, 5, 10, 2),
 (136, 1, 11, 2),
 (137, 4, 12, 2),
 (138, 4, 13, 2),
 (139, 5, 14, 2),
 (140, 5, 15, 2),
 (142, 2, 16, 2),
 (143, 5, 18, 2),
 (144, 4, 17, 2),
 (145, 5, 19, 2),
 (146, 1, 20, 2),
 (147, 1, 21, 2),
 (148, 4, 22, 2),
 (149, 2, 23, 2),
 (150, 2, 24, 2),
 (151, 2, 25, 2),
 (152, 5, 27, 2),
 (153, 3, 26, 2),
 (154, 4, 28, 2),
 (155, 4, 29, 2),
 (156, 3, 30, 2),
 (157, 3, 31, 2),
 (158, 3, 32, 2),
 (159, 3, 33, 2),
 (160, 4, 34, 2),
 (161, 3, 35, 2),
 (162, 5, 36, 2),
 (163, 5, 37, 2),
 (164, 2, 38, 2),
 (165, 3, 39, 2),
 (166, 5, 40, 2),
 (167, 3, 41, 2),
 (168, 4, 42, 2),
 (169, 5, 43, 2),
 (170, 5, 44, 2),
 (171, 3, 45, 2),
 (172, 2, 46, 2),
 (173, 5, 47, 2),
 (174, 3, 48, 2),
 (175, 5, 49, 2),
 (176, 4, 50, 2),
 (177, 4, 51, 2),
 (178, 2, 52, 2),
 (179, 2, 53, 2),
 (180, 4, 54, 2),
 (181, 4, 55, 2),
 (182, 4, 56, 2),
 (183, 5, 57, 2),
 (184, 5, 59, 2),
 (185, 4, 58, 2),
 (186, 4, 61, 2),
 (187, 3, 60, 2),
 (188, 4, 62, 2),
 (190, 3, 63, 2),
 (191, 5, 64, 2),
 (192, 4, 65, 2),
 (193, 4, 66, 2),
 (194, 5, 68, 2),
 (195, 2, 67, 2),
 (196, 3, 69, 2),
 (197, 3, 70, 2),
 (198, 5, 71, 2),
 (199, 3, 72, 2),
 (200, 4, 73, 2),
 (201, 5, 75, 2),
 (202, 5, 74, 2),
 (203, 3, 76, 2),
 (204, 4, 77, 2),
 (205, 3, 78, 2),
 (206, 5, 79, 2),
 (207, 2, 80, 2),
 (208, 3, 81, 2),
 (209, 5, 82, 2),
 (210, 4, 83, 2),
 (211, 5, 84, 2),
 (212, 5, 86, 2),
 (213, 4, 85, 2),
 (214, 3, 87, 2),
 (215, 2, 88, 2),
 (216, 4, 89, 2),
 (217, 5, 90, 2),
 (218, 5, 91, 2),
 (219, 4, 92, 2),
 (220, 4, 93, 2),
 (221, 3, 94, 2),
 (222, 1, 95, 2),
 (223, 2, 96, 2),
 (224, 2, 97, 2),
 (225, 4, 98, 2),
 (226, 4, 99, 2),
 (227, 5, 100, 2),
 (228, 4, 101, 2),
 (229, 3, 102, 2),
 (230, 4, 103, 2),
 (231, 5, 104, 2),
 (232, 4, 105, 2),
 (233, 4, 106, 2),
 (234, 5, 107, 2),
 (235, 4, 108, 2),
 (236, 5, 109, 2),
 (237, 3, 110, 2),
 (238, 5, 111, 2),
 (239, 3, 112, 2),
 (240, 3, 113, 2),
 (241, 4, 114, 2),
 (242, 4, 115, 2),
 (243, 4, 116, 2),
 (244, 3, 117, 2),
 (245, 5, 118, 2),
 (246, 5, 119, 2),
 (247, 5, 120, 2),
 (248, 5, 121, 2),
 (249, 5, 122, 2),
 (250, 3, 123, 2),
 (251, 5, 124, 2),
 (252, 5, 125, 2),
 (253, 4, 126, 2),
 (254, 5, 127, 2),
 (255, 4, 128, 2),
 (256, 5, 129, 2),
 (257, 4, 130, 2),
 (258, 4, 131, 2),
 (259, 2, 132, 2),
 (260, 5, 133, 2),
 (261, 5, 134, 2),
 (262, 5, 135, 2),
 (263, 4, 136, 2),
 (264, 3, 137, 2),
 (265, 5, 138, 2),
 (266, 5, 139, 2),
 (267, 5, 140, 2),
 (268, 4, 141, 2),
 (269, 4, 142, 2),
 (270, 5, 143, 2),
 (271, 3, 144, 2),
 (272, 5, 145, 2),
 (273, 4, 146, 2),
 (274, 2, 147, 2),
 (275, 2, 148, 2),
 (276, 4, 149, 2),
 (277, 3, 150, 2),
 (278, 5, 151, 2),
 (279, 5, 152, 2),
 (280, 4, 153, 2),
 (281, 4, 154, 2),
 (282, 5, 155, 2),
 (283, 3, 156, 2),
 (284, 5, 157, 2),
 (285, 4, 158, 2),
 (286, 5, 159, 2),
 (287, 5, 160, 2),
 (288, 4, 161, 2),
 (289, 5, 162, 2),
 (290, 3, 163, 2),
 (291, 4, 164, 2),
 (292, 2, 165, 2),
 (293, 5, 166, 2),
 (294, 3, 167, 2),
 (295, 5, 168, 2),
 (296, 4, 169, 2),
 (297, 4, 170, 2),
 (298, 2, 171, 2),
 (299, 3, 172, 2),
 (300, 5, 173, 2),
 (301, 4, 174, 2),
 (302, 4, 175, 2),
 (303, 4, 176, 2),
 (304, 5, 177, 2),
 (305, 3, 178, 2),
 (306, 3, 179, 2),
 (307, 5, 180, 2),
 (308, 4, 181, 2),
 (309, 5, 182, 2),
 (310, 5, 183, 2),
 (311, 4, 184, 2),
 (312, 5, 185, 2),
 (313, 5, 186, 2),
 (314, 3, 187, 2),
 (315, 5, 188, 2),
 (316, 4, 189, 2),
 (317, 5, 190, 2),
 (318, 3, 191, 2),
 (319, 3, 192, 2),
 (320, 4, 193, 2),
 (321, 3, 194, 2),
 (322, 5, 195, 2),
 (323, 2, 196, 2),
 (324, 4, 197, 2),
 (325, 5, 198, 2),
 (326, 5, 199, 2),
 (327, 3, 200, 2),
 (328, 3, 201, 2),
 (329, 4, 202, 2),
 (330, 4, 203, 2),
 (331, 2, 204, 2),
 (332, 1, 205, 2),
 (333, 3, 206, 2),
 (334, 3, 207, 2),
 (335, 4, 208, 2),
 (336, 2, 209, 2),
 (337, 3, 210, 2),
 (338, 5, 211, 2),
 (339, 5, 212, 2),
 (340, 4, 213, 2),
 (341, 3, 214, 2),
 (342, 3, 215, 2),
 (343, 4, 216, 2),
 (344, 5, 217, 2),
 (345, 5, 218, 2),
 (346, 5, 219, 2),
 (347, 5, 220, 2),
 (348, 4, 221, 2),
 (349, 5, 222, 2),
 (350, 5, 223, 2),
 (351, 2, 224, 2),
 (352, 2, 225, 2),
 (353, 2, 226, 2),
 (354, 4, 227, 2),
 (355, 2, 228, 2),
 (356, 5, 230, 2),
 (357, 4, 229, 2),
 (362, 5, 0, 5),
 (363, 5, 1, 5),
 (364, 5, 2, 5),
 (365, 5, 3, 5),
 (366, 5, 4, 5),
 (367, 5, 5, 5),
 (368, 5, 6, 5),
 (369, 5, 7, 5),
 (370, 5, 8, 5),
 (371, 5, 9, 5),
 (372, 5, 10, 5),
 (373, 5, 11, 5),
 (374, 5, 12, 5),
 (375, 5, 13, 5),
 (376, 5, 14, 5),
 (377, 5, 15, 5),
 (378, 5, 16, 5),
 (379, 5, 17, 5),
 (380, 5, 18, 5),
 (381, 5, 19, 5),
 (382, 5, 20, 5),
 (383, 5, 21, 5),
 (384, 5, 22, 5),
 (385, 5, 23, 5),
 (386, 5, 24, 5),
 (387, 5, 25, 5),
 (388, 5, 26, 5),
 (389, 5, 27, 5),
 (390, 5, 28, 5),
 (391, 5, 29, 5),
 (392, 5, 30, 5),
 (393, 4, 31, 5),
 (394, 5, 32, 5),
 (395, 4, 33, 5),
 (396, 5, 34, 5),
 (397, 4, 35, 5),
 (398, 3, 36, 5),
 (399, 4, 37, 5),
 (400, 5, 38, 5),
 (401, 5, 39, 5),
 (402, 4, 40, 5),
 (403, 5, 41, 5),
 (404, 5, 42, 5),
 (405, 4, 43, 5),
 (406, 4, 44, 5),
 (407, 5, 45, 5),
 (408, 4, 46, 5),
 (409, 5, 47, 5),
 (410, 4, 48, 5),
 (411, 5, 49, 5),
 (412, 5, 50, 5),
 (413, 5, 51, 5),
 (414, 4, 52, 5),
 (415, 4, 53, 5),
 (416, 5, 54, 5),
 (417, 5, 55, 5),
 (418, 4, 56, 5),
 (419, 4, 57, 5),
 (420, 4, 58, 5),
 (421, 4, 59, 5),
 (422, 4, 60, 5),
 (423, 4, 61, 5),
 (424, 5, 62, 5),
 (425, 5, 63, 5),
 (426, 4, 64, 5),
 (427, 4, 65, 5),
 (428, 5, 66, 5),
 (429, 4, 67, 5),
 (430, 5, 68, 5),
 (431, 5, 69, 5),
 (432, 5, 70, 5),
 (433, 4, 71, 5),
 (434, 4, 72, 5),
 (435, 5, 73, 5),
 (436, 4, 74, 5),
 (437, 4, 75, 5),
 (438, 4, 76, 5),
 (439, 4, 77, 5),
 (440, 4, 78, 5),
 (441, 3, 79, 5),
 (442, 4, 80, 5),
 (443, 4, 81, 5),
 (444, 3, 82, 5),
 (445, 4, 83, 5),
 (446, 4, 84, 5),
 (447, 3, 85, 5),
 (448, 4, 86, 5),
 (449, 3, 87, 5),
 (450, 3, 88, 5),
 (451, 5, 89, 5),
 (452, 5, 90, 5),
 (453, 4, 91, 5),
 (454, 4, 92, 5),
 (455, 4, 93, 5),
 (456, 4, 94, 5),
 (457, 4, 95, 5),
 (458, 4, 96, 5),
 (459, 5, 97, 5),
 (460, 4, 98, 5),
 (461, 4, 99, 5),
 (462, 5, 100, 5),
 (463, 4, 101, 5),
 (464, 5, 102, 5),
 (465, 5, 103, 5),
 (466, 4, 104, 5),
 (467, 4, 105, 5),
 (468, 5, 106, 5),
 (469, 4, 107, 5),
 (470, 4, 108, 5),
 (471, 5, 109, 5),
 (472, 4, 110, 5),
 (473, 4, 111, 5),
 (474, 4, 112, 5),
 (475, 5, 113, 5),
 (476, 4, 114, 5),
 (477, 5, 115, 5),
 (478, 3, 116, 5),
 (479, 3, 117, 5),
 (480, 3, 118, 5),
 (481, 5, 119, 5),
 (482, 4, 120, 5),
 (483, 5, 121, 5),
 (484, 5, 122, 5),
 (485, 3, 123, 5),
 (486, 3, 124, 5),
 (487, 3, 125, 5),
 (488, 3, 126, 5),
 (489, 3, 127, 5),
 (490, 3, 128, 5),
 (491, 3, 129, 5),
 (492, 2, 130, 5),
 (493, 4, 131, 5),
 (494, 2, 132, 5),
 (495, 4, 134, 5),
 (496, 3, 133, 5),
 (501, 5, 0, 4),
 (502, 4, 1, 4),
 (503, 5, 2, 4),
 (504, 5, 3, 4),
 (505, 5, 4, 4),
 (506, 5, 5, 4),
 (507, 5, 6, 4),
 (508, 4, 7, 4),
 (509, 3, 8, 4),
 (510, 5, 9, 4),
 (511, 4, 10, 4),
 (512, 4, 11, 4),
 (513, 5, 12, 4),
 (514, 2, 13, 4),
 (515, 2, 14, 4),
 (516, 5, 15, 4),
 (517, 5, 16, 4),
 (518, 4, 17, 4),
 (519, 5, 18, 4),
 (520, 4, 19, 4),
 (521, 5, 20, 4),
 (522, 5, 21, 4),
 (523, 5, 22, 4),
 (524, 3, 23, 4),
 (525, 5, 24, 4),
 (526, 5, 25, 4),
 (527, 5, 26, 4),
 (528, 4, 27, 4),
 (529, 2, 28, 4),
 (530, 1, 29, 4),
 (531, 5, 30, 4),
 (532, 5, 31, 4),
 (533, 5, 32, 4),
 (534, 5, 33, 4),
 (535, 4, 34, 4),
 (536, 3, 35, 4),
 (537, 4, 36, 4),
 (538, 5, 37, 4),
 (539, 5, 38, 4),
 (540, 5, 39, 4),
 (541, 3, 40, 4),
 (542, 4, 41, 4),
 (543, 5, 42, 4),
 (544, 4, 43, 4),
 (545, 3, 44, 4),
 (546, 5, 45, 4),
 (547, 5, 46, 4),
 (548, 4, 47, 4),
 (549, 5, 48, 4),
 (550, 5, 49, 4),
 (551, 5, 50, 4),
 (552, 4, 51, 4),
 (553, 3, 52, 4),
 (554, 5, 53, 4),
 (555, 5, 54, 4),
 (556, 4, 55, 4),
 (557, 3, 56, 4),
 (558, 3, 57, 4),
 (559, 5, 58, 4),
 (560, 3, 59, 4),
 (561, 4, 60, 4),
 (562, 5, 61, 4),
 (563, 4, 62, 4),
 (564, 3, 63, 4),
 (565, 5, 64, 4),
 (566, 4, 65, 4),
 (567, 1, 66, 4),
 (568, 5, 67, 4),
 (569, 5, 68, 4),
 (570, 5, 69, 4),
 (571, 4, 70, 4),
 (572, 5, 71, 4),
 (573, 3, 72, 4),
 (574, 5, 73, 4),
 (575, 4, 74, 4),
 (576, 5, 75, 4),
 (577, 3, 76, 4),
 (578, 2, 77, 4),
 (579, 4, 78, 4),
 (580, 4, 79, 4),
 (581, 5, 80, 4),
 (582, 5, 81, 4),
 (583, 4, 82, 4),
 (584, 3, 83, 4),
 (585, 3, 84, 4),
 (586, 4, 85, 4),
 (587, 3, 86, 4),
 (588, 3, 87, 4),
 (589, 2, 88, 4),
 (590, 5, 89, 4),
 (591, 4, 90, 4),
 (592, 5, 91, 4),
 (593, 4, 92, 4),
 (594, 5, 93, 4),
 (595, 5, 94, 4),
 (596, 5, 95, 4),
 (597, 3, 96, 4),
 (598, 4, 97, 4),
 (599, 4, 98, 4),
 (600, 5, 99, 4),
 (601, 4, 100, 4),
 (602, 5, 101, 4),
 (603, 4, 102, 4),
 (604, 4, 103, 4),
 (605, 2, 104, 4),
 (606, 5, 105, 4),
 (607, 5, 106, 4),
 (608, 5, 108, 4),
 (609, 4, 107, 4),
 (610, 5, 109, 4),
 (611, 4, 110, 4),
 (612, 2, 111, 4),
 (613, 3, 112, 4),
 (614, 5, 113, 4),
 (615, 4, 114, 4),
 (616, 5, 115, 4),
 (617, 4, 116, 4),
 (618, 3, 117, 4),
 (619, 5, 118, 4),
 (620, 4, 119, 4),
 (621, 3, 120, 4),
 (622, 5, 121, 4),
 (623, 5, 122, 4),
 (624, 4, 123, 4),
 (625, 3, 124, 4),
 (626, 5, 125, 4),
 (627, 5, 126, 4),
 (628, 4, 127, 4),
 (629, 4, 128, 4),
 (630, 5, 129, 4),
 (631, 3, 130, 4),
 (632, 3, 131, 4),
 (633, 5, 132, 4),
 (634, 4, 133, 4),
 (635, 3, 134, 4),
 (636, 5, 135, 4),
 (637, 5, 136, 4),
 (638, 4, 137, 4),
 (639, 5, 138, 4),
 (640, 3, 139, 4),
 (641, 4, 140, 4),
 (642, 5, 141, 4),
 (643, 5, 142, 4),
 (644, 5, 143, 4),
 (645, 4, 144, 4),
 (646, 4, 145, 4),
 (647, 3, 146, 4),
 (648, 5, 147, 4),
 (649, 4, 148, 4),
 (650, 5, 149, 4),
 (651, 5, 150, 4),
 (652, 4, 151, 4),
 (653, 5, 152, 4),
 (654, 3, 153, 4),
 (655, 1, 154, 4),
 (656, 5, 155, 4),
 (657, 5, 156, 4),
 (658, 5, 157, 4),
 (659, 4, 158, 4),
 (660, 3, 159, 4),
 (661, 5, 160, 4),
 (662, 5, 161, 4),
 (663, 4, 162, 4),
 (664, 3, 163, 4),
 (665, 5, 164, 4),
 (666, 5, 165, 4),
 (667, 3, 166, 4),
 (668, 4, 167, 4),
 (669, 5, 168, 4),
 (670, 5, 169, 4),
 (671, 5, 170, 4),
 (672, 4, 171, 4),
 (673, 3, 172, 4),
 (674, 5, 173, 4),
 (675, 5, 174, 4),
 (676, 5, 175, 4),
 (677, 4, 176, 4),
 (678, 5, 177, 4),
 (679, 3, 178, 4),
 (680, 2, 179, 4),
 (681, 5, 180, 4),
 (682, 4, 181, 4),
 (683, 3, 182, 4),
 (684, 4, 183, 4),
 (685, 5, 184, 4),
 (686, 3, 185, 4),
 (687, 2, 186, 4),
 (688, 3, 187, 4),
 (689, 2, 188, 4),
 (690, 5, 189, 4),
 (691, 3, 190, 4),
 (692, 5, 191, 4),
 (693, 2, 192, 4),
 (694, 5, 193, 4),
 (695, 1, 194, 4),
 (696, 2, 195, 4),
 (697, 5, 196, 4),
 (698, 3, 197, 4),
 (699, 2, 198, 4),
 (700, 4, 199, 4),
 (701, 4, 200, 4),
 (702, 5, 201, 4),
 (703, 4, 202, 4),
 (704, 5, 203, 4),
 (705, 2, 204, 4),
 (706, 2, 205, 4),
 (707, 4, 206, 4),
 (708, 3, 207, 4),
 (709, 3, 208, 4),
 (710, 2, 209, 4),
 (711, 4, 210, 4),
 (712, 5, 211, 4),
 (713, 1, 212, 4),
 (714, 5, 213, 4),
 (715, 5, 214, 4),
 (716, 4, 215, 4),
 (717, 3, 216, 4),
 (718, 2, 217, 4),
 (719, 5, 218, 4),
 (720, 5, 219, 4),
 (721, 5, 220, 4),
 (722, 5, 221, 4),
 (723, 3, 222, 4),
 (724, 4, 223, 4),
 (725, 5, 224, 4),
 (726, 3, 225, 4),
 (727, 5, 226, 4),
 (728, 4, 227, 4),
 (729, 2, 228, 4),
 (730, 5, 229, 4),
 (731, 4, 230, 4),
 (732, 5, 145, 6),
 (733, 3, 70, 6),
 (734, 1, 114, 6),
 (735, 3, 164, 6),
 (736, 5, 177, 6),
 (737, 4, 230, 6),
 (738, 3, 188, 6),
 (739, 5, 155, 6),
 (740, 5, 141, 6),
 (741, 3, 102, 6),
 (742, 1, 62, 6),
 (743, 3, 26, 6),
 (744, 5, 0, 6),
 (745, 4, 1, 6),
 (746, 4, 8, 6),
 (747, 4, 43, 6),
 (748, 5, 45, 6),
 (749, 5, 78, 6),
 (750, 3, 76, 6),
 (751, 1, 95, 6),
 (752, 1, 106, 6),
 (753, 5, 109, 6),
 (754, 3, 123, 6),
 (755, 1, 128, 6),
 (756, 5, 160, 6),
 (757, 4, 158, 6),
 (758, 5, 180, 6),
 (759, 4, 181, 6),
 (760, 3, 195, 6),
 (761, 4, 198, 6),
 (762, 4, 208, 6),
 (763, 4, 202, 6),
 (764, 5, 185, 6),
 (765, 4, 191, 6),
 (766, 1, 213, 6),
 (767, 3, 216, 6),
 (768, 4, 219, 6),
 (769, 5, 223, 6),
 (770, 4, 224, 6),
 (771, 3, 226, 6),
 (772, 1, 152, 6),
 (773, 4, 148, 6),
 (774, 5, 132, 6),
 (775, 4, 134, 6),
 (776, 3, 136, 6),
 (777, 4, 118, 6),
 (778, 5, 83, 6),
 (779, 4, 85, 6),
 (780, 5, 89, 6),
 (781, 3, 92, 6),
 (782, 5, 135, 8),
 (783, 5, 136, 8),
 (784, 4, 137, 8),
 (785, 5, 138, 8),
 (786, 5, 139, 8),
 (787, 5, 140, 8),
 (788, 4, 141, 8),
 (789, 5, 142, 8),
 (790, 4, 143, 8),
 (791, 5, 144, 8),
 (792, 5, 145, 8),
 (793, 5, 146, 8),
 (794, 4, 147, 8),
 (795, 4, 148, 8),
 (796, 5, 149, 8),
 (797, 5, 150, 8),
 (798, 5, 151, 8),
 (799, 5, 152, 8),
 (800, 5, 153, 8),
 (801, 5, 154, 8),
 (802, 5, 155, 8),
 (803, 5, 156, 8),
 (804, 5, 157, 8),
 (805, 5, 158, 8),
 (806, 4, 159, 8),
 (807, 4, 160, 8),
 (808, 4, 161, 8),
 (809, 4, 162, 8),
 (810, 4, 163, 8),
 (811, 4, 164, 8),
 (812, 4, 165, 8),
 (813, 4, 166, 8),
 (814, 4, 167, 8),
 (815, 4, 168, 8),
 (816, 4, 169, 8),
 (817, 4, 170, 8),
 (818, 4, 171, 8),
 (819, 4, 172, 8),
 (820, 4, 173, 8),
 (821, 5, 174, 8),
 (822, 4, 175, 8),
 (823, 5, 176, 8),
 (824, 4, 177, 8),
 (825, 5, 178, 8),
 (826, 4, 179, 8),
 (827, 4, 180, 8),
 (828, 4, 181, 8),
 (829, 4, 182, 8),
 (830, 3, 183, 8),
 (831, 4, 184, 8),
 (832, 4, 185, 8),
 (833, 4, 186, 8),
 (834, 4, 187, 8),
 (835, 5, 188, 8),
 (836, 4, 189, 8),
 (837, 3, 190, 8),
 (838, 3, 191, 8),
 (839, 3, 192, 8),
 (840, 3, 193, 8),
 (841, 3, 194, 8),
 (842, 3, 195, 8),
 (843, 3, 196, 8),
 (844, 4, 197, 8),
 (845, 3, 198, 8),
 (846, 4, 199, 8),
 (847, 3, 200, 8),
 (848, 3, 201, 8),
 (849, 3, 202, 8),
 (850, 3, 203, 8),
 (851, 4, 204, 8),
 (852, 4, 205, 8),
 (853, 4, 206, 8),
 (854, 4, 207, 8),
 (855, 3, 208, 8),
 (856, 3, 209, 8),
 (857, 3, 210, 8),
 (858, 2, 211, 8),
 (859, 3, 212, 8),
 (860, 3, 213, 8),
 (861, 3, 214, 8),
 (862, 3, 215, 8),
 (863, 3, 216, 8),
 (864, 3, 217, 8),
 (865, 3, 218, 8),
 (866, 3, 219, 8),
 (867, 2, 220, 8),
 (868, 3, 221, 8),
 (869, 2, 222, 8),
 (870, 3, 223, 8),
 (871, 3, 224, 8),
 (872, 3, 225, 8),
 (873, 3, 226, 8),
 (874, 3, 227, 8),
 (875, 3, 228, 8),
 (876, 3, 229, 8),
 (877, 2, 230, 8),
 (878, 5, 1, 7),
 (879, 5, 3, 7),
 (880, 5, 5, 7),
 (881, 3, 6, 7),
 (882, 5, 11, 7),
 (883, 5, 16, 7),
 (884, 2, 17, 7),
 (885, 3, 9, 7),
 (886, 5, 21, 7),
 (887, 5, 22, 7),
 (888, 3, 24, 7),
 (889, 3, 23, 7),
 (890, 5, 27, 7),
 (891, 5, 29, 7),
 (892, 5, 34, 7),
 (893, 3, 31, 7),
 (894, 5, 42, 7),
 (895, 5, 43, 7),
 (896, 1, 52, 7),
 (897, 1, 57, 7),
 (898, 5, 86, 7),
 (899, 5, 87, 7),
 (900, 5, 88, 7),
 (901, 5, 75, 7),
 (902, 1, 74, 7),
 (903, 2, 73, 7),
 (904, 4, 72, 7),
 (905, 1, 94, 7),
 (906, 5, 99, 7),
 (907, 5, 104, 7),
 (908, 4, 108, 7),
 (909, 5, 142, 7),
 (910, 4, 131, 7),
 (911, 5, 140, 7),
 (912, 5, 149, 7),
 (913, 4, 146, 7),
 (914, 4, 147, 7),
 (915, 4, 148, 7),
 (916, 5, 160, 7),
 (917, 3, 171, 7),
 (918, 5, 167, 7),
 (919, 5, 186, 7),
 (920, 5, 187, 7),
 (921, 5, 178, 7),
 (922, 4, 180, 7),
 (923, 5, 201, 7),
 (924, 3, 195, 7),
 (925, 4, 202, 7),
 (926, 4, 203, 7),
 (927, 4, 204, 7),
 (928, 5, 211, 7),
 (929, 4, 217, 7),
 (930, 3, 218, 7),
 (931, 4, 223, 7),
 (932, 4, 224, 7),
 (933, 4, 225, 7),
 (934, 2, 229, 7),
 (935, 2, 230, 7),
 (936, 5, 114, 7),
 (937, 2, 109, 7)]

In [113]:
user_id,user_name = [],[]
for i in users:
    user_id.append(i[0])
    user_name.append(i[1])
users_df = pd.DataFrame({'user_id':user_id, 'user_name':user_name})
users_df

   user_id   user_name
0        3        Cora
1        7       Hexin
2        5          Sq
3        8        Sqsq
4        2        Yier
5        4       Yisen
6        6      Yisenw
7        1  zhanghexin

In [114]:
episode_id,user_id_fk,rating = [],[],[]
for i in ratings:
    episode_id.append(i[2])
    user_id_fk.append(i[3])
    rating.append(i[1])
ratings_df = pd.DataFrame({'episode_id':episode_id, 'user_id':user_id_fk, 'rating':rating})
ratings_df

     episode_id  user_id  rating
0             3        1       5
1             4        1       2
2             5        1       2
3             6        1       5
4             7        1       1
..          ...      ...     ...
911         225        7       4
912         229        7       2
913         230        7       2
914         114        7       5
915         109        7       2

[916 rows x 3 columns]

In [115]:
data = users_df.merge(ratings_df,on='user_id',how='left')
data

     user_id   user_name  episode_id  rating
0          3        Cora           0       5
1          3        Cora           3       4
2          3        Cora           4       4
3          3        Cora           6       4
4          3        Cora           7       5
..       ...         ...         ...     ...
911        1  zhanghexin         170       2
912        1  zhanghexin         171       2
913        1  zhanghexin         193       2
914        1  zhanghexin         225       4
915        1  zhanghexin         211       2

[916 rows x 4 columns]

In [ ]:
data[data['user_name']=='zhanghexin')]

In [133]:
origin_mat = data.pivot(index='episode_id',columns='user_name',values='rating').T
origin_mat

episode_id,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
user_name,,,,,,,,,,,,,,,,,,,,,
Cora,5.0,NaN,NaN,4.0,4.0,NaN,4.0,5.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hexin,NaN,5.0,NaN,5.0,NaN,5.0,3.0,NaN,NaN,3.0,...,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,2.0,2.0
Sq,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sqsq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0
Yier,3.0,4.0,5.0,3.0,5.0,4.0,5.0,3.0,4.0,2.0,...,4.0,5.0,5.0,2.0,2.0,2.0,4.0,2.0,4.0,5.0
Yisen,5.0,4.0,5.0,5.0,5.0,5.0,5.0,4.0,3.0,5.0,...,5.0,3.0,4.0,5.0,3.0,5.0,4.0,2.0,5.0,4.0
Yisenw,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,5.0,4.0,NaN,3.0,NaN,NaN,NaN,4.0
zhanghexin,NaN,NaN,NaN,5.0,2.0,2.0,5.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN

In [116]:
mat = data.pivot(index='episode_id',columns='user_name',values='rating').T
mat

episode_id,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
user_name,,,,,,,,,,,,,,,,,,,,,
Cora,5.0,NaN,NaN,4.0,4.0,NaN,4.0,5.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hexin,NaN,5.0,NaN,5.0,NaN,5.0,3.0,NaN,NaN,3.0,...,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,2.0,2.0
Sq,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sqsq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0
Yier,3.0,4.0,5.0,3.0,5.0,4.0,5.0,3.0,4.0,2.0,...,4.0,5.0,5.0,2.0,2.0,2.0,4.0,2.0,4.0,5.0
Yisen,5.0,4.0,5.0,5.0,5.0,5.0,5.0,4.0,3.0,5.0,...,5.0,3.0,4.0,5.0,3.0,5.0,4.0,2.0,5.0,4.0
Yisenw,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,5.0,4.0,NaN,3.0,NaN,NaN,NaN,4.0
zhanghexin,NaN,NaN,NaN,5.0,2.0,2.0,5.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in range(mat.shape[1]):
    mat[i] = mat[i].apply(lambda x: x-np.mean(mat[i]))

In [125]:
mat

episode_id,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
user_name,,,,,,,,,,,,,,,,,,,,,
Cora,0.4,NaN,NaN,-0.5,-0.2,NaN,-0.5,1.4,NaN,-2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hexin,NaN,0.6,NaN,0.5,NaN,0.8,-1.5,NaN,NaN,-0.2,...,NaN,NaN,-0.2,0.4,0.8,NaN,NaN,NaN,-1.5,-1.4
Sq,0.4,0.6,0.0,0.5,0.8,0.8,0.5,1.4,1.0,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sqsq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,-1.333333,-1.2,-0.6,-0.2,-0.25,-0.666667,0.666667,-0.5,-1.4
Yier,-1.6,-0.4,0.0,-1.5,0.8,-0.2,0.5,-0.6,0.0,-1.2,...,0.0,1.666667,0.8,-1.6,-1.2,-1.25,0.333333,-0.333333,0.5,1.6
Yisen,0.4,-0.4,0.0,0.5,0.8,0.8,0.5,0.4,-1.0,1.8,...,1.0,-0.333333,-0.2,1.4,-0.2,1.75,0.333333,-0.333333,1.5,0.6
Yisenw,0.4,-0.4,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,0.8,0.4,NaN,-0.25,NaN,NaN,NaN,0.6
zhanghexin,NaN,NaN,NaN,0.5,-2.2,-2.2,0.5,-2.6,NaN,NaN,...,NaN,NaN,NaN,NaN,0.8,NaN,NaN,NaN,NaN,NaN

In [163]:
np.isnan(mat.loc['Cora',1])

True

In [161]:
type(mat.loc['Cora',1])

numpy.float64

In [ ]:
def calc_cos_sim(a,b):
    if sum(b) != 0 and sum(a) != 0:
        result = np.dot(a/np.sqrt(np.sum((a)**2)),b/np.sqrt(np.sum((b)**2)))
    else:
        result = None
    return result

In [175]:
from tqdm import tqdm

cosine_similarity = np.zeros((mat.shape[1],mat.shape[1]))
for i in tqdm(range(mat.shape[1])):
    for j in range(mat.shape[1]):
        if i < j:
            temp = mat[[i,j]].dropna(axis=0)
            a = np.array(temp[i])
            b = np.array(temp[j])
            if np.sum(a) != 0 and np.sum(b) != 0:
                cosine_similarity[i][j] = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
            else:
                cosine_similarity[i][j] = None
cosine_similarity = cosine_similarity.T + cosine_similarity
cosine_similarity

100%|██████████| 231/231 [00:28<00:00,  8.09it/s]

array([[ 0.        ,  0.35043832,         nan, ...,  0.51449576,
        -0.0766965 , -0.67675297],
       [ 0.        ,  0.        ,         nan, ...,  1.        ,
        -0.9459053 , -0.93422349],
       [ 0.        ,  0.        ,  0.        , ...,         nan,
                nan,         nan],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.73854895, -0.92402659],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,         nan],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [168]:
def Item_Item_Filter(username):
    result = np.zeros(mat.shape[1])
    for i in range(mat.shape[1]):
        if np.isnan(origin_mat.loc[username, i]):
            coeff,cos_sim = [],[]
            for idx, j in enumerate(cosine_similarity[i]):
                if j > 0.5 and not np.isnan(origin_mat.loc[username,idx]):
                    coeff.append(origin_mat.loc[username,idx])
                    cos_sim.append(j)
            if coeff != [] and cos_sim != []:
                result[i] = np.dot(np.array(coeff),np.array(cos_sim)) / np.sum(cos_sim)
    return result.argsort()[::-1][:5]
Scores = Item_Item_Filter('Cora')    
Scores

array([0.        , 4.00586847, 0.        , 0.        , 0.        ,
       3.15761762, 0.        , 0.        , 3.9356326 , 0.        ,
       0.        , 3.76265381, 3.40917567, 3.52635602, 3.85117315,
       3.0190932 , 3.74635164, 0.        , 0.        , 0.        ,
       0.        , 0.        , 3.74635164, 3.70381369, 3.48643577,
       3.5827958 , 3.02471458, 3.56512143, 0.        , 3.65532329,
       0.        , 3.28307065, 3.40917567, 0.        , 4.15454526,
       0.        , 3.27079068, 3.57085495, 3.5827958 , 3.40917567,
       0.        , 3.53505519, 3.74635164, 3.60095737, 0.        ,
       3.44440452, 3.39912687, 0.        , 0.        , 0.        ,
       3.40917567, 3.86151642, 3.43270821, 3.39912687, 3.40917567,
       3.86151642, 3.40401784, 2.94035403, 3.18690757, 0.        ,
       3.40917567, 3.18690757, 3.07474715, 0.        , 3.08542471,
       0.        , 3.68445354, 3.39912687, 0.        , 0.        ,
       0.        , 3.57085495, 4.15454526, 3.14267096, 2.66340619,
       3.32903299, 3.23506571, 3.40401784, 3.724827  , 0.        ,
       3.39912687, 0.        , 3.27079068, 0.        , 0.        ,
       3.18214704, 3.63857803, 3.62373247, 0.        , 3.44440452,
       3.40401784, 3.08542471, 2.89211746, 0.        , 0.        ,
       3.13168584, 3.53505519, 0.        , 0.        , 3.87164785,
       0.        , 0.        , 0.        , 3.86151642, 3.5708209 ,
       0.        , 2.87764261, 3.12024655, 3.02062771, 2.80799416,
       3.40917567, 0.        , 3.86151642, 3.40917567, 0.        ,
       3.40917567, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 2.84970853, 3.12024655,
       0.        , 3.44663971, 0.        , 2.77372074, 0.        ,
       0.        , 3.65421105, 3.69631905, 3.69044432, 0.        ,
       0.        , 3.09608096, 3.51200215, 0.        , 0.        ,
       0.        , 5.        , 3.53255461, 0.        , 3.78458385,
       0.        , 3.67272713, 3.41365235, 3.5990686 , 3.53255461,
       3.51200215, 3.69694202, 2.24469626, 3.71551751, 3.69818385,
       0.        , 3.51200215, 0.        , 4.04485814, 0.        ,
       0.        , 0.        , 3.00871829, 0.        , 2.62701614,
       3.46048542, 0.        , 4.01182273, 3.03418878, 2.65622043,
       2.65622043, 0.        , 4.25406753, 0.        , 0.        ,
       3.26043954, 4.25406753, 2.87048643, 4.29172581, 3.71551751,
       0.        , 0.        , 0.        , 2.59706699, 3.26043954,
       3.45854614, 0.        , 4.28155305, 3.51502581, 3.26043954,
       3.00871829, 3.43317075, 3.6597506 , 2.946175  , 0.        ,
       0.        , 3.40351295, 3.6597506 , 0.        , 3.00871829,
       3.26043954, 3.35672679, 0.        , 2.58338013, 4.29172581,
       3.96928337, 3.50357053, 4.25406753, 0.        , 4.25406753,
       3.26043954, 3.06937297, 0.        , 2.66865152, 2.94455201,
       3.26043954, 2.99581697, 0.        , 0.        , 3.07615381,
       0.        , 2.70144903, 3.026945  , 2.99452376, 3.36916431,
       3.7363677 , 3.23253231, 3.03418878, 4.25406753, 2.72323663,
       2.98384074])